// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk_AOkxPO56IBiZ_b8wuxq1G6SF4u9kW0',
    appId: '1:707090792139:web:5fa2974fb36b29f53b654e',
    messagingSenderId: '707090792139',
    projectId: 'tulsa-parkport-dev',
    authDomain: 'tulsa-parkport-dev.firebaseapp.com',
    storageBucket: 'tulsa-parkport-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOYCpPVCTRh_GG_oCgSbFqPnpqr4Bd-b0',
    appId: '1:707090792139:android:af652a6e7a5cdcba3b654e',
    messagingSenderId: '707090792139',
    projectId: 'tulsa-parkport-dev',
    storageBucket: 'tulsa-parkport-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWtWlDCa6tx_NwTnULRhwFnzhpOyCSdos',
    appId: '1:707090792139:ios:a4549e565d8ee2783b654e',
    messagingSenderId: '707090792139',
    projectId: 'tulsa-parkport-dev',
    storageBucket: 'tulsa-parkport-dev.appspot.com',
    iosClientId: '707090792139-jocku9hfcjcooofggqpp8a4jorkkarag.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkPort',
  );
}
